---
- name: Restart apache
  service: name={{ playbook.apache.Debian.apache }} state=restarted
  when: ansible_os_family == 'Debian'

- name: Restart apache
  service: name={{ playbook.apache.RedHat.apache }} state=restarted
  when: ansible_os_family == 'RedHat'
