---
# Setting apache server settings
max_clients: "{{ playbook.apache.common.max_clients }}"
max_spare_servers: "{{ (max_clients|int ** 0.5)|int + 2}}"
min_spare_servers: "{{ (max_spare_servers|int / 2)|int }}"

# Setting Prefork MPM
prefork_start_servers: 4
prefork_min_spare_servers: "{{min_spare_servers}}"
prefork_max_spare_servers: "{{max_spare_servers}}"
prefork_server_limit: "{{max_clients}}"
prefork_max_clients: "{{max_clients}}"
prefork_max_requests_per_child: 1000
prefork_listen_backlog: "{{max_clients|int * 2}}"

# Setting Worker MPM
worker_start_servers: 4
worker_max_clients: 1024
worker_min_spare_threads: 64
worker_max_spare_threads: 192
worker_threads_per_child: 64
worker_max_requests_per_child: 0
