---
# Setting Prefork MPM
prefork_start_servers: "{{ playbook.apache.common.start_servers }}"
prefork_min_spare_servers: "{{ playbook.apache.common.min_spare_servers }}"
prefork_max_spare_servers: "{{ playbook.apache.common.max_spare_servers }}"
prefork_server_limit: "{{ playbook.apache.common.server_limit }}"
prefork_max_clients: "{{ playbook.apache.common.max_clients }}"
prefork_max_requests_per_child: "{{ playbook.apache.common.max_requests_per_child }}"
prefork_listen_backlog: "{{ playbook.apache.common.listen_backlog }}"

# Setting Worker MPM
worker_start_servers: 4
worker_max_clients: 1024
worker_min_spare_threads: 64
worker_max_spare_threads: 192
worker_threads_per_child: 64
worker_max_requests_per_child: 0
