---
- name: Setup default apache firewall rules - RedHat
  command: "/sbin/iptables -I INPUT 1 -p tcp --dport {{ item }} -j ACCEPT"
  with_items: playbook.apache.common.open_firewall_ports
  when: ansible_os_family == 'RedHat'

- name: Setup default apache firewall rules - Debian
  command: ufw allow {{ item }}
  with_items: playbook.apache.common.open_firewall_ports
  when: ansible_os_family == 'Debian'
